library(stm)
#deter <- stm(poliblog5k.docs, poliblog5k.voc, K=5, prevalence=~rating, data=poliblog5k.meta, max.em.its = 2, control=list(method="BFGS"))
deter <- stm(poliblog5k.docs, poliblog5k.voc, K=5, prevalence=~rating, data=poliblog5k.meta, max.em.its = 2, control=list(method="BFGS", randomize=TRUE, order_sigma=TRUE, order_beta=TRUE))
#rand <- stm(poliblog5k.docs, poliblog5k.voc, K=5, prevalence=~rating, data=poliblog5k.meta, seed=13, max.em.its = 100, control=list(randomize=TRUE, method="BFGS"))
#all.equal(deter, rand)